### ISSUE TITLE
multiple R for Windows terminal front-end instances

### ISSUE THREAD

**Issue by pholck** [REditorSupport/vscode-R#1002]
I love this extension, but am fairly new to VScode, using this for just a few months. However I have noticed that there are a ginormous number of "R for Windows terminal front-end" tasks running whenever I fire up vs code with this extension. This is prior to launching an R terminal (radian or otherwise). Yes, it IS correlated to how many files I have open in the editor with a *.r extension (I think). But I have some 30 tasks (as per task manager, Windows 11) running that are "R for Windows terminal front-end", while I have 4 or 5 files open to edit. 

While many of these instances are relatively low memory, there are so many of them that it has really taxed the memory capacity of my laptop whenever I use vscode. 

I fully expect that I am doing something stupid and have some wrong setting, but any suggestions for reducing the number of R for Windows terminal front-end instances that run when I start VScode would be most welcome!

**Comment by albertosantini** [comment]
At least the R instances are closed when vscode quit or the extension is deactivated. ;)

To mitigate the number of instances I would give a try to `R_LANGSVR_POOL_SIZE` as decribed here: https://github.com/REditorSupport/vscode-R/issues/735#issuecomment-945589930

About the consumption of memory - this really is the panic point, more than the number of R instances (and I would change the title of the issue) - I may give a look at "memory" keyword in different opened or closed issues. Just to be aware about the attempts and the vision of extension team about this topic.

At the moment, it works in this way by design, but there is lot of space for the improvement, but I understand the refactoring involves a lot of work (you know, contributions are welcome). Here @renkun-ken may give us their opinion.
