### ISSUE TITLE
vscode-R asking to install languageserver even though its installed (with "r.lsp.args": ["--vanilla"] and renv)

### ISSUE THREAD

**Issue by adamaltmejd** [REditorSupport/vscode-R#1021]
Loading `languageserver` and other vscode-R packages through main library in `renv` projects using the setup described in the last post here https://github.com/REditorSupport/vscode-R/issues/584.

But recently I started getting this popup on every launch.

```R package {languageserver} is required to enable R language service features such as code completion, function signature, find references, etc. Do you want to install it? ```

Seems vscode-R is not following `"r.lsp.args": ["--vanilla"]`?

**Comment by renkun-ken** [comment]
It is caused by the R processes to detect if languageserver is installed is not started with `r.lsp.args`. I'll take a closer look at this when I got a chance.

**Comment by adamaltmejd** [comment]
Exactly, thanks. Can't figure out why someone would want the detection process not to use the same settings as the lsp, so should work to let the process just follow that setting as well.

**Comment by ray-p144** [comment]
I believe I am having a related issue.

I just started using this extension after a long history of using RStudio and wanting to explore new options, so I am not sure if this is a new issue or not. But enabling the R language server causes R to bootstrap the installation of the renv package into the project's root directory (i.e., `proj_root/library/R-4.1/x86_64-w64-mingw32/renv`), and ignores the `renv/` directory (i.e., `proj_root/renv/library/...`).

I set `"r.lsp.args": ["--vanilla"]`, assuming that it would fix my problem, but to no avail. After finding this opened issue, I believe the problem is likely to be the R processes detecting if language server is installed as well.

**Comment by adamaltmejd** [comment]
I still get `Install package `httpgd` to use vscode-R with httpgd!` even though httpgd is installed in my main library.

**Comment by walrossker** [comment]
Hi @renkun-ken, in trying to setup `languageserver`, I'm getting the same warning as above:

`R package {languageserver} is required to enable R language service features such as code completion, function signature, find references, etc. Do you want to install it?`

 ...and in the "Output" pane, it says `R Language Server (23912) exited with exit code 10`.

Some context: I use `renv` to manage packages and I keep those project-specific libraries outside of the project folders. I've used the `languageserversetup` package to install the languageserver library in the folder where I keep project specific `renv` libraries and have included the code from `languageserversetup::languageserver_add_to_rprofile` in .Rprofile to point the project to that folder. 

It sounds like the added feature in #1071 might help with this, but when I point the `r.lsp.libPath` to my languageserver library, the same error persists. 

Any thoughts on where I'm going wrong?
