### ISSUE TITLE
For consistency: Use .Rmd instead of .rmd for New Draft

### ISSUE THREAD

**Issue by jooyoungseo** [REditorSupport/vscode-R#1048]
The default file extention given by `R Markdown: New Draft` is ".rmd", not ".Rmd". However, for templates requiring a new folder, the default extension is ".Rmd". I would suggest we change to `Untitled-1.Rmd` for consistency.

**Comment by renkun-ken** [comment]
When the template creates a standalone file, we create an untitled document that contains the file content and give it a language identifier (in this case, `rmd`) instead of a file extension. It is VS Code to put the language identifier as the file extension when user tries to save the untitled document.

**Comment by jooyoungseo** [comment]
I am closing this issue because this is not a bug, and an expected behavior.
