### ISSUE TITLE
Option to open Viewer in external browser (like for R Help)

### ISSUE THREAD

**Issue by fisher-j** [REditorSupport/vscode-R#1072]
**Is your feature request related to a problem? Please describe.**
Sometimes it is useful to be able to open the contents of the Viewer in an external browser.

**Describe the solution you'd like**
R Plot, Help and Markdown all have a command to open in external browser, I would like to have this option for Viewer contents as well.

**Describe alternatives you've considered**
It is possible to get this functionality by disabling Viewer.

**Additional context**
![image](https://user-images.githubusercontent.com/63136705/162633582-8ad839b8-7cc7-428b-9bc8-8d0bc3a66cba.png)
![image](https://user-images.githubusercontent.com/63136705/162633635-9effb6f4-8e14-4c73-839b-0ba3c93c77a5.png)

**Comment by renkun-ken** [comment]
Thanks for the feature request! It is straightforward to implement. However, it won't work with remote development scenario since the file is on a remote server rather than local. I think we'll need [Live Preview](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) for remote scenario.

**Comment by fisher-j** [comment]
Thanks for responding.
Just for clarification, my specific use case involves viewing large html
tables for data exploration, but when viewing smaller tables, the built in
Viewer is desirable.
