### ISSUE TITLE
Attach active terminal doesn't work with screen on a remote server

### ISSUE THREAD

**Issue by zslastman** [REditorSupport/vscode-R#1276]
Hey guys.
I'm connecting with ssh to a remote server. The extension works perfectly if I 'create R terminal' - I can plots just fine with httpgd, the attached R session updates in the status bar etc.. However I"d like to be able to log back into a pre-existing screen session and attach to one of the R sessions I've left runnning overnight or whatever.

I've followed the instructions in advanced usage, so I am running the init-R script, Sys.getenv('TERM_PROGRAM') gives 'vscode', and I can execute .vsc.attach() in the screen session. However this doesn't update the R session attached to vscode - the status bar doesn't change and I can't receive plots. This is kind of inconsistently the case - usually if I start a fresh screen session and open R there it works - but of course this then kind of defeats the purpose of screen. Clearly there's something not getting updated, but e.g. running .First.sys() again doesn't work. Any ideas?

(oh and thank you for writing an incredibly useful tool!)

My Machine: 12.6 (21G115)
remote machine: Linux comp-01-dd5 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
Vscode version: Version: 1.74.0 (Universal)

**Comment by d-golzato** [comment]
Hi zlastman! I've been trying many times to reattach to a remote R session running on a screen.
After a long session of noobie trial and error, I found that attaching to a screen running the Radian terminal, instead
of the default one, works. All the environment variables are also automatically loaded.
Let me know if it works for you!

As a feature suggestion, I think it would be incredible to be able to attach to a remote R session through ssh
tunnelling, in a similar way to how you connect to a jupyter server through vscode. In this way you would just need a conda environment with the R kernel, instead of a vscode server with all the extensions installed remotely. Unfortunately I lack the coding skills and knowledge to formulate a solution.

Thanks for this amazing extension, now I'm almost able to completely replace Rstudio and work remotely without the need to use Rstudio server + Rstudio pro.
