### ISSUE TITLE
Hilight user-defined functions.

### ISSUE THREAD

**Issue by MrJGao** [REditorSupport/vscode-R#377]
Is there any plan to add the feature that can highlight user-defined functions? Just want to distinguish them from system/library functions. Thanks.

**Comment by renkun-ken** [comment]
I guess we could implement this via [Semantic Tokens](https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens) in languageserver since only languageserver parses the user documents and knows the source information of each token in the document.
