### ISSUE TITLE
After installing gc-excelviewer, message about it not being installed keeps appearing

### ISSUE THREAD

**Issue by andycraig** [REditorSupport/vscode-R#399]
While experimenting with the `Preview` command problems I also found that even after installing the gc-excelviewer the message about it not being installed kept appearing. The message went away after restarting VSCode, but this seems like a bug.

_Originally posted by @andycraig in https://github.com/Ikuyadeu/vscode-R/issues/92#issuecomment-582397603_

**Comment by ManuelHentschel** [comment]
I'm not familiar with this part of the extension but I noticed that we check if the excelviewer extension is installed and active but do not try to activate it ourselves. 

https://github.com/Ikuyadeu/vscode-R/blob/39c5b20f65c0cdf16eaa2680f092d68b0241dfc6/src/preview.ts#L118-L120

This probably won't work as intended if the extension is installed but hasn't been triggered to activate yet. This might be fixed by something along the lines of
``` ts
if (iscsv !== undefined && iscsv.isActive) {
    return true;
} else if(iscsv !== undefined) {
    await iscsv.activate();
    return true;
}
```

or we skip the `isActive` check if we don't actually need the extension to be active at that time.
