### ISSUE TITLE
Help files are not viewable when working with remote connection

### ISSUE THREAD

**Issue by nathaneastwood** [REditorSupport/vscode-R#466]
I'm not entirely convinced this is a vscode-R problem, so apologies in advanced if it isn't.

When working on a remote connection (ssh into a Linux env), if I use `devtools::load_all("pkg")`, and I try to view the development help file, I am faced with the following:

```
Using development documentation for MyFunction
VSCode WebView has restricted access to local file.
Opening in external browser...
Browsing file:///tmp/RtmpM6oemu/Rtxtf8e36c15798a.html
```

As well as the following pop up box

![image](https://user-images.githubusercontent.com/9799530/100095444-c57a6800-2e5a-11eb-8d56-62cbd37e6b51.png)

My default for `getOption("help_type")` is `"html"`. If I change this to `"text"` then everything works fine and I see my help file in the console. I can open the `html` file (`file:///tmp/RtmpM6oemu/Rtxtf8e36c15798a.html`) perfectly fine although it of course doesn't render. I am not certain how I give WebView access to development docs?

FWIW:

```
    "r.rterm.windows": "C://location//to//R.exe",
    "r.rterm.linux": "location/to/radian",
    "r.rterm.option": [""],
    "r.bracketedPaste": true,
    "r.lsp.debug": false,
    "r.lsp.diagnostics": false,
    "r.alwaysUseActiveTerminal": true,
    "r.sessionWatcher": true,
```

vscode-R 1.6.1
VSCode 1.51.1

**Comment by renkun-ken** [comment]
Related to #383.

**Comment by ManuelHentschel** [comment]
If I understood things correctly, the help function from `as.environment('devtools_shims')` (attached after using `load_all`) generates an object with class `dev_topic`, which is printed by [`print.dev_topic`](https://github.com/r-lib/pkgload/blob/00702b49c7bff59151e0df4e359c50df130d9f09/R/dev-help.r#L55:L82).

In that print function, a temporary html help file is generated and passed to `utils::browseURL()`, which the browser from init.R cannot show in a webivew, since vscode webviews cannot access arbitrary files.

Instead the filename is passed to the vscode-R extension, which tries to open the file in an [external browser](https://github.com/ManuelHentschel/vscode-R/blob/2ba15ccdc65746d48c0fe4de1263fe9ee9c43259/src/session.ts#L184) but fails, since the file is located on the remote machine.

I guess fixing this problem would be possible by modifying/overwriting any of the functions involved in that chain, but I'm not really sure, what the best approach would be to do this.

**Comment by renkun-ken** [comment]
@ManuelHentschel You are right, this is largely due to the limitation of WebView security policies and how it is managed to access allowed resources.

**Comment by mmyrte** [comment]
This apparently also affects package development in dev containers.

I don't know much about this (great!) plugin, but there is an `rstudioapi` emulation layer, right? It may also be possible to overload the `previewRd` function, see [here](https://github.com/r-lib/pkgload/blob/bf6ad9132c28c82f02b264c159d72b89ee917639/R/dev-help.r#L69)

**Comment by markschat** [comment]
Hi, just wanted to contribute some details (Remote SSH from Win to Linux)

- I develop a package that is already installed 
- run `devtools::document`
- run `?my_func`

that returns (as described above):
```
ℹ Rendering development documentation for "my_function"
VSCode WebView has restricted access to local file.
Opening in external browser...
Browsing file:///tmp/RtmpEhDFQJ/Rtxt5a0a5d3d65d9.html
```

If I use the recommended `F1` keybinding the "old" docs are shown as expected but not the most recent ones generated by `devtools::document`
```
{
    "key": "f1",
    "command": "r.helpPanel.openForSelection",
    "when": "editorTextFocus && editorLangId == 'r' || editorTextFocus && editorLangId == 'rmd'"
}
```

Same thing happens when I use the extension buttons (HELP PAGES > Help Topics ... > my_package > my_func) - the old docs are loaded instead of the most current ones.
