### ISSUE TITLE
Load jsonlite and rlang from custom lib.loc so session watcher can start from renv project

### ISSUE THREAD

**Issue by adamaltmejd** [REditorSupport/vscode-R#584]
Right now when running R from a renv project where the packages are not installed the session watcher does not work but throws:

```
VSCode R Session Watcher requires jsonlite, rlang. Please install manually in order to use VSCode-R.
```

I can of course install the packages in the project but don't want my projects to include unnecessary dependencies. Would it be possible to set a custom library location for requireNamespace() somehow?

**Comment by renkun-ken** [comment]
This could be done in https://github.com/Ikuyadeu/vscode-R/blob/master/R/.Rprofile by sourcing project `.Rprorfile` created by renv after sourcing session watcher `init.R`.

Would you like to try editing your project `.Rprofile` by putting the following code before renv init:

```r
if (!exists(".vsc")) {
  source(file.path(
    Sys.getenv(if (.Platform$OS.type == "windows") "USERPROFILE" else "HOME"),
    ".vscode-R", "init.R")
  )
}
```

**Comment by adamaltmejd** [comment]
Thanks! That would work, but now I'm sourcing `init.R` from ~/.Rprofile which seems better. Sourcing `init.R` from within the project has the same effect as including the packages in renv: I introduce an unneeded dependency on VSCode.

Is there maybe a way to get R to source `~/.Rprofile` before project `.Rprofile`?

**Comment by renkun-ken** [comment]
The "R: Create R terminal" is trying to mimic the R's native behavior that if a project `.Rprofile` is present, then it will not source `~/.Rprofile`.

It works for you then I think we could provide a vscode setting so that user could customize the order of execution in `https://github.com/Ikuyadeu/vscode-R/blob/master/R/.Rprofile`:

1. optionally source user profile
2. source project profile
3. source session watcher script

**Comment by adamaltmejd** [comment]
Ahh right I set `RENV_CONFIG_USER_PROFILE=TRUE` in `~/.Renviron` to ensure my user Rprofile is still sourced. 

Problem with "R: Create R terminal" is that I'm using tmux on a server with SSH Remote and need to start R from within tmux.

**Comment by renkun-ken** [comment]
> Problem with "R: Create R terminal" is that I'm using tmux on a server with SSH Remote and need to start R from within tmux.

Yes, if you are using tmux to preserve your R session, then you need to customize your profile to source session watcher on your own, which actually gives you more freedom of control the order and behavior.

**Comment by adamaltmejd** [comment]
Exactly, thats what I'm trying to do :). Trying to do it without bogging down my research project with personal coding preferences that the others working in the project are not interested in.

Was thinking that the easiest way would be to somehow get the init.R script to use a custom library instead of renv, but the alternative would be to get `~/.Rprofile` to be sourced through renv before project `.Rprofile` which would require changed to that package instead.

**Comment by danielbasso** [comment]
When using renv, after loading the project custom environment for the first time I have to install the `languageserver` and whatever dependency it needs. These won't be included in the `renv.lock` file because it scans from calls inside your code; so, it's a bit annoying, of course, but I don't count as "introducing unneeded dependency", since when you share the code and others perform an `renv::restore()`, these packages won't be installed.

**Comment by adamaltmejd** [comment]
Indeed thats what I'm doing right now. Works, but a bit frustrating when opening new projects etc.

**Comment by adamaltmejd** [comment]
Think I found a solution: Install languageserver etc in your main library, then set the env variable R_LIBS_USER in .bashrc or similar and run lsp in vanilla: `"r.lsp.args": ["--vanilla"]`. Seems to work!
