### ISSUE TITLE
Send code to terminal tab in editor group

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#682]
https://github.com/microsoft/vscode/issues/10546 allows user to move integrated terminal to editor group, which is included in the latest insider build.

However, "Run selection" does not seem to work with the terminal tabs. We might need to take a look at the related API.

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/4662568/123438532-5a1c9280-d603-11eb-96bf-81c5bc2ae6e3.png">

**Comment by renkun-ken** [comment]
The [Terminals in the editor area](https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area) is released, looks like we need to support it now.

**Comment by ElianHugh** [comment]
On my end, it looks like sending code to the editor terminal *does* work, but vscode-R then attempts to focus the old terminal panel. Seems like `term.show` is being weird

**Comment by renkun-ken** [comment]
Yes, same here, it will unnecessarily reveal the terminal pane, which then gets the focus and sending to active terminal will send code to the shell in terminal instead of the R terminal. Focus again on the R terminal and then things will work as usual.

Is there a way to determine if the terminal is in editor? If so, we should reveal the editor tab instead of the terminal pane.

**Comment by ElianHugh** [comment]
Right. 

I've had a look around and I haven't had any luck in determining where the terminal is. `vscode.window.terminals` & `vscode.window.activeTerminal` don't have any location information, and terminals don't show up in `vscode.visibleTextEditors`

**Comment by MilesMcBain** [comment]
I had a look at this too and found the same @ElianHugh, there seems to be no way via the API at the moment to identify terminals that are open in the editor area.

What I did notice is that if I avoid running `show()` by setting option `source.focus = "none"` then I can send code an editor area terminal without it popping the terminal panel.

So that should mostly work, but if user accidentally opens a new file in the same group as the terminal it could get hidden and not auto show. I noticed there is discussion on the VSCode repo to create the ability to lock editor groups to avoid this: https://github.com/microsoft/vscode/issues/124709

I couldn't find a bug report about the `show()` behaviour, so I am going to make one.

**Comment by MilesMcBain** [comment]
Another annoying thing I just noticed is that if the user sets `terminal.integrated.defaultLocation = editor` then new terminals get created 'over the top' of the current text document that has focus in the editor group.

**Comment by MilesMcBain** [comment]
Created feature request for option to avoid opening editor area terminals on top of active text editor: https://github.com/microsoft/vscode/issues/129172

**Comment by MilesMcBain** [comment]
It seems the `show()` bug is already fixed and they have added to feature request to their current backlog which is encouraging.

**Comment by renkun-ken** [comment]
I tried the latest insider and it works now, but sending code to terminal in editor is still a bit buggy. For example, once we show the terminal and execute "Terminal: Move terminal into editor area", sending code to active terminal might not work at first, then focus the terminal in editor and get back to the editor, and then send code again, now it should work.

**Comment by MilesMcBain** [comment]
It sounds like we need to make a new bug report!
