### ISSUE TITLE
Extention of the new `knitr` background process using current workspace elements

### ISSUE THREAD

**Issue by domiden** [REditorSupport/vscode-R#711]
**Is your feature request related to a problem? Please describe.**
First of all, many thanks for your hard work!
At the moment, if I have understood it correctly, you need to load needed data or the workspace within the R markdown file. However, the preparation of those data might take quite some time, and therefore difficult for realising a quick review.

**Describe alternatives you've considered**
So, I was wondering if the `knitr` background process could be extended to extract all environmental elements, which are needed for processing such as needed data structure and function, automatically from the current workspace, save them to a temporary file? Then provide it to the `knitr` background process.

**Additional context**
System infos:
- `Fedora` Linux OS v34 (`Gnome` v40.3)
- `R` v4.0.5
- VS Code using `vscode-R` v2.1.0

**Comment by renkun-ken** [comment]
You might want to just send `rmarkdown::render()` to terminal and show the output webpage.

**Comment by domiden** [comment]
Thanks for your quick response. I'm aware about that, and using it all the time. But the same argument could be used for the `knitr` background process, I guess.

**Comment by renkun-ken** [comment]
The background process is fully managed so that we kill/start one on file update. Working with a user session is tricky since the terminal could be anything: normal R, busy R, some tmux window in copy mode, etc, it will be much unpredictable to communicate with a user session via sending commands to terminal like this.

If you want to save data from your user session, then you might need to run `save.image("data.RData")` and in your Rmd it needs to restore the variables via `load("data.RData")` in the beginning.

When the data becomes quite large, it would be dangerous to do this, since both `save.image()` and `load()` are not interruptable. The entire session might hang for quite a long time. That's why we don't do automatically saving/restoring at the moment.

**Comment by domiden** [comment]
> When the data becomes quite large, it would be dangerous to do this, since both save.image() and load() are not interruptable.

Yeah, that's actually the problem I ran into. I just saved the entire workspace to a temporary file and insert it in the `Rmd` file of choice (quick and dirty). Some files get quite large, and filtering variables beforehand might be quite cumbersome. I also see the problem, that also just a set of variable could cause the background process hanging for a while. So, I was wondering if the introduction of a user specific size or time limit (set in the preferences), allowing the process to terminate with a warning to the user reaching that limit, might be a reasonable solution to that problem? Perhaps, alternatively inform the user that the process might hang for a while and allowing the user to continuous or terminate the process. Additionally, the warning could also inform the user that the process might be instable and terminate unexpectedly.
