### ISSUE TITLE
Spurious function names in help search

### ISSUE THREAD

**Issue by renkun-ken** [REditorSupport/vscode-R#730]
Click "Open help topic using `?`" and type a function name like `to_string`, then the result might contain several spurious results which are not exported functions of the package but marked as e.g. `languageserver::to_string`.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/4662568/126723784-2ebb34f2-2bc7-44b4-9559-171d4b03b59e.png">

**Comment by ManuelHentschel** [comment]
With my installation, `languageserver::to_string` is not documented at all (`#' @noRd`) and also does not show up in the quickpick.

Assuming that `to_string` is documented but not exported, the command "Open help topic using `?`" still shows it in the suggestions list. To some extent, this is in line with the behavior of the normal `?` command, since e.g. `? languageserver::to_string` should work, even though `languageserver::to_string` throws an error.

I guess it would be better to show this function as `languageserver:::to_string` to indicate that it is not exported.

I'll have to check how to implement this cleanly, since currently the help provider does not know whether a topic refers to an exported function or not.
