### ISSUE TITLE
VSCode's `Duplicate Workspace`

### ISSUE THREAD

**Issue by Fred-Wu** [REditorSupport/vscode-R#774]
VSCode allows to open a duplicated workspace, and it looks like working with R as well. 

In the duplicated workspace, the same R session would be attached, and everything typed in the main terminal would be shown in the duplicated workspace, including plots. 

However,

1. any objects created in the main workspace cannot be called or used in the duplicated workspace (except that plots would appear in the duplicated window);
2. once the duplicated workspace is closed, the R session losts connection even in the main workspace. Still can do everything, but no more shown in the workspace, and with following error messages.

Is `Duplicate Workspace` something that can be truly supported for R so that objects can be shared?

```
r$> .vsc.attach()
Error in file(con, "w") : cannot open the connection
In addition: Warning message:
In file(con, "w") :
  cannot open file 'C:\Users\xxx\AppData\Local\Temp\RtmpUDYfJA/vscode-R/addins.json': No such file or directory
```
```
r$> plot(1:10)
cannot open the connectionwarning messages from top-level task callback 'vsc.globalenv'
Warning message:
In file(con, "w") :
  cannot open file 'C:\Users\xxx\AppData\Local\Temp\RtmpUDYfJA/vscode-R/globalenv.json': No such file or directory
```

**Comment by renkun-ken** [comment]
Never heard of the term `Duplicate workspace`. Would you like to point to an official documentation or something about this?

**Comment by Fred-Wu** [comment]
> 
> 
> Never heard of the term `Duplicate workspace`. Would you like to point to an official documentation or something about this?

You can create one just in `File` -> `Duplicate Workspace`. 

It will open a second window. Then, clicking on the R session ID in the main window, you can see the objects would appear in the duplicated R workspace.

**Comment by renkun-ken** [comment]
I could reproduce this.

It is caused by that when an R terminal is started in either of the instances of duplicate workspaces, both instances watch the same `~/.vscode-R/request.log` and receive the "attach" request since both find that the working directory of the session is identical to the current workspace folder and conclude that it should attach to the session.

If we could somehow distinguish the two instances of the same workspace folder and let the handling of the requests not only check the working directory but an identity of the request sender (e.g. vscode pid), then duplicate workspaces could work properly.
