### ISSUE TITLE
Line-by-line execution restarts terminal on SSH connection

### ISSUE THREAD

**Issue by suwayyah** [REditorSupport/vscode-R#849]
**Describe the bug**
I asked this in the vscode repository but maybe I should post it here:
https://github.com/microsoft/vscode/issues/135385

**Comment by formix** [comment]
There is a workaround meanwhile. In the bash terminal opened by VSCode, I launch R in there then it is fine. Afterward CTRL+ENTER sends line of code in that terminal without issue.

But not sending the code to the "R Interactive" terminal window properly is an issue since things don't appear in the R Workspace pane.

The R Workspace left pane offers to open a Workspace file. Where shall be that workspace file for the R teminal I start manually (as explained above)?
